(Tue Mar 25 16:47:45 2025)(10.9352 [s])[Default,Printers][Error][Fatal]:
ERROR: A problem has occurred in the printer utilities.
Error! Tried to write block to dataset (name=Invalidation Code), but target index (0) is inside the current dataset extents (dset size=1000), i.e. some of the target slots are already used! This is a bug, please report it.

YAML-ready parameter values at failed point:
  MSSM19atQ:
    Ad_3: 1142.11
    Ae_3: -531.67
    Au_3: 6822.76
    M1: -1487.21
    M2: -519.44
    M3: 2476.08
    Qin: 2000
    SignMu: 1
    TanBeta: 13.6299
    mHd2: -667.105
    mHu2: -823.055
    md2_12: 10000
    md2_3: 4826.08
    me2_12: 10000
    me2_3: 10000
    ml2_12: 10000
    ml2_3: 10000
    mq2_12: 10000
    mq2_3: 3755.61
    mu2_12: 10000
    mu2_3: 4271.33
  StandardModel_SLHA2:
    CKM_A: 0.814
    CKM_etabar: 0.353
    CKM_lambda: 0.22537
    CKM_rhobar: 0.117
    GF: 1.16638e-05
    alpha1: 0
    alpha2: 0
    alphaS: 0.117807
    alphainv: 127.95
    delta13: 0
    mBmB: 4.18
    mCmC: 1.28
    mD: 0.0047
    mE: 0.000510999
    mMu: 0.105658
    mNu1: 0
    mNu2: 0
    mNu3: 0
    mS: 0.096
    mT: 174.59
    mTau: 1.77686
    mU: 0.0022
    mZ: 91.1876
    theta12: 0.58376
    theta13: 0.15495
    theta23: 0.76958

Raised at: line 329 in function void Gambit::Printers::HDF5DataSet<T>::write_buffer(const T (&)[100000], std::size_t, std::size_t, bool) [with T = int; std::size_t = long unsigned int] of /work/gambit/Printers/include/gambit/Printers/printers/hdf5printer_v2.hpp.
--<>--<>--<>--<>--<>--<>--<>--
